kernel:
  #image: linuxkit/kernel:4.9.39
  image: linuxkit/kernel-ubuntu:4.4.0-80
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:838b772355a8690143b37de1cdd4ac5db725271f
  - linuxkit/runc:d5cbeb95bdafedb82ad2cf11cff1a5da7fcae630
  - linuxkit/containerd:e33e0534d6fca88e1eb86897a1ea410b4a5d722e
  #TODO ca-certificates modified to include cluster certs
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: binfmt
    image: linuxkit/binfmt:0bde4ebd422099f45c5ee03217413523ad2223e5
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  # analyse content (AWS metadata)
  - name: metadata
    image: linuxkit/metadata:f5d4299909b159db35f72547e4ae70bd76c42c6c
    net: host
    binds:
      - /dev:/dev
      - /var:/var
      - /etc/resolv.conf:/etc/resolv.conf
    capabilities:
      - CAP_SYS_ADMIN

  # Format and mount disks
  # - name: diskmanager
  #   image:
  #   command: []
  # Get ericeira.json from config/drive or S3
  # - name: ericeira json
  #   image:
  #   command: []
  # Hostname
  # DNS: Resolved - Not available, only static DNS
  # OVERRIDES ?
  # Network Configuration (this is the hardest container)
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  # - name: timesyncd
  #   image:
  # - name: blackbox_exporter
  #   image:
  # - name: node_exporter
  #   image:
  - name: getty
    image: linuxkit/getty:894eef1e5f62f3bc31de8ffaff2b6c0e093c4595
    env:
     - INSECURE=true
    binds:
     - /dev:/dev
     - /var:/var
     - /etc/resolv.conf:/etc/resolv.conf
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  #TODO: sshd with key gen and certificate
  - name: sshd
    image: linuxkit/sshd:5dc5c3c4470c85f6c89f0e26b9d477ae4ff85a3c
    # binds:
    #  - /var/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  # - name: nginx
  #   image: nginx:alpine
  #   capabilities:
  #    - CAP_NET_BIND_SERVICE
  #    - CAP_CHOWN
  #    - CAP_SETUID
  #    - CAP_SETGID
  #    - CAP_DAC_OVERRIDE
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  # - path: etc/containerd/config.toml
  #   contents: |
  #     state = "/run/containerd"
  #     root = "/var/lib/containerd"
  #     snapshotter = "io.containerd.snapshotter.v1.overlayfs"
  #     differ = "io.containerd.differ.v1.base-diff"
  #     subreaper = false
  #
  #     [grpc]
  #     address = "/run/containerd/containerd.sock"
  #     uid = 0
  #     gid = 0
  #
  #     [debug]
  #     address = "/run/containerd/debug.sock"
  #     level = "info"
  #
  #     [metrics]
  #     address = ":13337"
  # - path: etc/linuxkit-config
  #   metadata: yaml
trust:
  org:
    - linuxkit
    - library
